import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";
import TopHeader from "@/components/layouts/top-header";

export const metadata: Metadata = {
  title: "bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <TopHeader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
